### ISSUE TITLE
What is the asset multiplier?

### ISSUE THREAD

**Issue by markmarijnissen** [stephenreid321/stephenreid#25]
Hi Stephen,

I was reading the source code of the metastrategy and I noticed this line:
```ruby
with_multipliers[ticker] += holding.weight * strategy.nscore_score * (asset.multiplier || 1)
```
Here, the weight of the strategy is multiplied by the performance score, and then weighter by a multiplier.

These multipliers are used in rebalancing:
```ruby
with_multipliers, without_multipliers = Strategy.assets_weighted
weights = Strategy.proposed(with_multipliers, n: n)
```

I traced back the origin of this multiplier to a form on your website: https://github.com/stephenreid321/stephenreid/blob/2b754da138f57b5fecf8cd2b4d6b7bbf0d8144db/app/controllers/crypto.rb#L37

Therefore, I concluded that you manually weight certain assets (coins, not strategies). Am I right?

(BTW, although the route is not protected, I get a 404 on a page like https://stephenreid.net/assets/USDT/mutiplier)

**Comment by stephenreid321** [comment]
Yes, you're right, the multipliers are manual/not obtained from ICONOMI.
